--   local function gh(repo) return 'https://github.com/' .. repo end
--   vim.pack.add {
--     gh 'ThePrimeagen/harpoon',
--     gh 'nvim-lua/plenary.nvim',
--   }
--
--   local harpoon = require 'harpoon'
--   harpoon:setup()
--
--   vim.keymap.set('n', '<leader>a', function()
--     harpoon:list():add()
--   end, { desc = '[a]dd to harpoon' })
--   vim.keymap.set('n', '<leader>e', function()
--     harpoon.ui:toggle_quick_menu(harpoon:list())
--   end, { desc = '[e]xplore harpoon menu' })
